# Generated by Django 3.2.15 on 2022-08-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
