# Generated by Django 3.2.15 on 2022-08-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
    ]
